theme: jekyll-theme-midnight
title: Concept Welder
author: Sankalpa Abeygunawardhana
description: Sankalpa's blog

- name: Generate the sitemap
  id: sitemap
  uses: cicirello/generate-sitemap@v1
  with:
    base-url-path: https://conceptwelder.com/
